# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Avadh_Demo_Project' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
pod 'Firebase/Database'
  # Pods for Avadh_Demo_Project

end
